### ISSUE TITLE
[Issue] - Hi-res images not loaded in full resolution

### ISSUE THREAD

**Issue by crank-chips** [BooYeu/react-native-reanimated-viewer#21]
Platforms: iOS, Android (but more noticeable on Android)

ImageViewer doesn't load the hi-res image properly. It's pixelated when zoomed in.
There is an 8k test image can be found by the link: https://i.ibb.co/cyLmJWh/8k-test.png
The same link is used in the code. And when the image is opened in ImageViewer and zoomed in you can see that it's pixelated, but looks sharp in the browser.

https://github.com/BooYeu/react-native-reanimated-viewer/assets/17419029/ca31779c-51c0-4cab-8918-cbcd918249f2

Code:
```
import {Dimensions, Image, View} from "react-native";
import * as React from "react";
import {ImageViewer, ImageWrapper} from "react-native-reanimated-viewer";
import {useRef} from "react";
import {FlatList} from "react-native-gesture-handler";

const images = Array.from({length: 50}, (_, index) => {
    return {
        thumbNailUri: `https://picsum.photos/id/${index + 10}/980/551`
    };
});

export const TestRNViewer = () => {
    const imageRef = useRef(null);

    return (
        <>
            <ImageViewer
                ref={imageRef}
                doubleTapScale={20}
                maxScale={20}
                data={images.map((el) => ({
                    key: `key-${el.thumbNailUri}`,
                    source: {uri: "https://i.ibb.co/cyLmJWh/8k-test.png"}
                }))}
            />
            <View style={{backgroundColor: "rgb(15, 15, 15)"}}>
                <FlatList
                    data={images}
                    keyExtractor={(item) => item.thumbNailUri}
                    initialNumToRender={5}
                    renderItem={({item, index}) => (
                        <ImageWrapper
                            key={item.thumbNailUri}
                            viewerRef={imageRef}
                            index={index}
                            source={{
                                uri: item.thumbNailUri,
                            }}
                        >
                            <Image source={{uri: item.thumbNailUri,}}
                                   style={{width: Dimensions.get("screen").width, height: 250, marginBottom: 10}}/>
                        </ImageWrapper>
                    )}
                    showsVerticalScrollIndicator={false}
                />
            </View>

        </>
    );
}

**Comment by BooYeu** [comment]
fixed in v1.3.1

**Comment by crank-chips** [comment]
@BooYeu this is still reproducible on Android.

<img width="849" alt="Screenshot 2023-07-11 at 4 09 39 PM" src="https://github.com/BooYeu/react-native-reanimated-viewer/assets/17419029/4c20052c-a3f1-4197-8d7c-5a2338f175ae">
